export type StockDirectoryEntry = {
  ticker: string;
  name: string;
  exchange: "NASDAQ" | "NYSE";
  sector: string;
};

export const popularStocks: StockDirectoryEntry[] = [
  { ticker: "AAPL", name: "Apple", exchange: "NASDAQ", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft", exchange: "NASDAQ", sector: "Technology" },
  { ticker: "GOOGL", name: "Alphabet Class A", exchange: "NASDAQ", sector: "Communication Services" },
  { ticker: "GOOG", name: "Alphabet Class C", exchange: "NASDAQ", sector: "Communication Services" },
  { ticker: "META", name: "Meta Platforms", exchange: "NASDAQ", sector: "Communication Services" },
  { ticker: "TSLA", name: "Tesla", exchange: "NASDAQ", sector: "Consumer Discretionary" },
  { ticker: "AMD", name: "Advanced Micro Devices", exchange: "NASDAQ", sector: "Semiconductors" },
  { ticker: "INTC", name: "Intel", exchange: "NASDAQ", sector: "Semiconductors" },
  { ticker: "AVGO", name: "Broadcom", exchange: "NASDAQ", sector: "Semiconductors" },
  { ticker: "ORCL", name: "Oracle", exchange: "NYSE", sector: "Technology" },
  { ticker: "CRM", name: "Salesforce", exchange: "NYSE", sector: "Technology" },
  { ticker: "ADBE", name: "Adobe", exchange: "NASDAQ", sector: "Technology" },
  { ticker: "NFLX", name: "Netflix", exchange: "NASDAQ", sector: "Communication Services" },
  { ticker: "QCOM", name: "Qualcomm", exchange: "NASDAQ", sector: "Semiconductors" },
  { ticker: "IBM", name: "IBM", exchange: "NYSE", sector: "Technology" },
  { ticker: "CSCO", name: "Cisco Systems", exchange: "NASDAQ", sector: "Technology" },
  { ticker: "NOW", name: "ServiceNow", exchange: "NYSE", sector: "Technology" },
  { ticker: "PLTR", name: "Palantir Technologies", exchange: "NASDAQ", sector: "Technology" },
  { ticker: "SMCI", name: "Super Micro Computer", exchange: "NASDAQ", sector: "Technology" },
  { ticker: "ARM", name: "Arm Holdings", exchange: "NASDAQ", sector: "Semiconductors" },
  { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", exchange: "NYSE", sector: "Semiconductors" },
  { ticker: "ASML", name: "ASML Holding", exchange: "NASDAQ", sector: "Semiconductor Equipment" },
  { ticker: "AMAT", name: "Applied Materials", exchange: "NASDAQ", sector: "Semiconductor Equipment" },
  { ticker: "LRCX", name: "Lam Research", exchange: "NASDAQ", sector: "Semiconductor Equipment" },
  { ticker: "KLAC", name: "KLA Corporation", exchange: "NASDAQ", sector: "Semiconductor Equipment" },
  { ticker: "JPM", name: "JPMorgan Chase", exchange: "NYSE", sector: "Financials" },
  { ticker: "BAC", name: "Bank of America", exchange: "NYSE", sector: "Financials" },
  { ticker: "GS", name: "Goldman Sachs", exchange: "NYSE", sector: "Financials" },
  { ticker: "MS", name: "Morgan Stanley", exchange: "NYSE", sector: "Financials" },
  { ticker: "V", name: "Visa", exchange: "NYSE", sector: "Financials" },
  { ticker: "MA", name: "Mastercard", exchange: "NYSE", sector: "Financials" },
  { ticker: "PYPL", name: "PayPal", exchange: "NASDAQ", sector: "Financials" },
  { ticker: "COIN", name: "Coinbase Global", exchange: "NASDAQ", sector: "Financials" },
  { ticker: "BRK-B", name: "Berkshire Hathaway Class B", exchange: "NYSE", sector: "Financials" },
  { ticker: "WMT", name: "Walmart", exchange: "NYSE", sector: "Consumer Staples" },
  { ticker: "COST", name: "Costco Wholesale", exchange: "NASDAQ", sector: "Consumer Staples" },
  { ticker: "HD", name: "Home Depot", exchange: "NYSE", sector: "Consumer Discretionary" },
  { ticker: "LOW", name: "Lowe's", exchange: "NYSE", sector: "Consumer Discretionary" },
  { ticker: "MCD", name: "McDonald's", exchange: "NYSE", sector: "Consumer Discretionary" },
  { ticker: "SBUX", name: "Starbucks", exchange: "NASDAQ", sector: "Consumer Discretionary" },
  { ticker: "KO", name: "Coca-Cola", exchange: "NYSE", sector: "Consumer Staples" },
  { ticker: "PEP", name: "PepsiCo", exchange: "NASDAQ", sector: "Consumer Staples" },
  { ticker: "PG", name: "Procter & Gamble", exchange: "NYSE", sector: "Consumer Staples" },
  { ticker: "JNJ", name: "Johnson & Johnson", exchange: "NYSE", sector: "Healthcare" },
  { ticker: "PFE", name: "Pfizer", exchange: "NYSE", sector: "Healthcare" },
  { ticker: "LLY", name: "Eli Lilly", exchange: "NYSE", sector: "Healthcare" },
  { ticker: "UNH", name: "UnitedHealth Group", exchange: "NYSE", sector: "Healthcare" },
  { ticker: "MRK", name: "Merck", exchange: "NYSE", sector: "Healthcare" },
  { ticker: "ABBV", name: "AbbVie", exchange: "NYSE", sector: "Healthcare" },
  { ticker: "XOM", name: "Exxon Mobil", exchange: "NYSE", sector: "Energy" },
  { ticker: "CVX", name: "Chevron", exchange: "NYSE", sector: "Energy" },
  { ticker: "CAT", name: "Caterpillar", exchange: "NYSE", sector: "Industrials" },
  { ticker: "BA", name: "Boeing", exchange: "NYSE", sector: "Industrials" },
  { ticker: "GE", name: "GE Aerospace", exchange: "NYSE", sector: "Industrials" },
  { ticker: "UBER", name: "Uber Technologies", exchange: "NYSE", sector: "Industrials" },
  { ticker: "ABNB", name: "Airbnb", exchange: "NASDAQ", sector: "Consumer Discretionary" },
  { ticker: "DIS", name: "Walt Disney", exchange: "NYSE", sector: "Communication Services" },
  { ticker: "NKE", name: "Nike", exchange: "NYSE", sector: "Consumer Discretionary" },
];
